create table if not exists users (
    id bigint primary key generated by default as identity,
    username varchar(200) unique,
    email text unique,
    password text,
    profile_text text
);

create table if not exists tags (
    id bigint primary key generated by default as identity,
    tag varchar(200) unique
);

create table if not exists posts (
    id bigint primary key generated by default as identity,
    title text,
    slug text,
    author bigint references users (id),
    posted_at timestamp,
    updated_at timestamp default null,
    content text,
    unique (slug, author)
);

create table if not exists subscriptions (
    id bigint primary key generated by default as identity,
    user_id bigint references users (id),
    author bigint references users (id),
    unique (user_id, author)
);

create table if not exists posts_tags (
    id bigint primary key generated by default as identity,
    tag_id bigint references tags (id),
    post_id bigint references posts (id),
    unique (tag_id, post_id)
);
